title: Habib Bashirr Lawal
logo: ![IMG_E1126](https://github.com/user-attachments/assets/3e4aaba4-5b3e-425c-8064-e81004a81481)
description: B.Eng Electrical, Data Scientist.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
