title: Habib Bashir Lawal
logo: /pictures/IMG_E1126
Description: Data Scientist
show_download: true
Theme: jekyll-theme-minimal
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
